export const RESOURCES_MOCK = [
  {
    id: "r1",
    name: "2026_수능특강_영어_변형문제_3강.pdf",
    type: "pdf",
    size: "2.4MB",
    date: "2026-01-15",
    category: "english",
  },
  {
    id: "r2",
    name: "미적분_킬러문항_기출분석.pdf",
    type: "pdf",
    size: "5.1MB",
    date: "2026-01-20",
    category: "math",
  },
  {
    id: "r3",
    name: "국어_현대시_필수작품_100선.pdf",
    type: "pdf",
    size: "8.3MB",
    date: "2026-01-10",
    category: "korean",
  },
  {
    id: "r4",
    name: "3월_학력평가_대비_모의고사.pdf",
    type: "pdf",
    size: "3.2MB",
    date: "2026-02-01",
    category: "common",
  },
  {
    id: "r5",
    name: "영어_빈칸추론_공략법.mp4",
    type: "video",
    size: "150MB",
    date: "2026-01-05",
    category: "english",
  },
  {
    id: "r6",
    name: "수학1_삼각함수_공식정리.jpg",
    type: "image",
    size: "1.2MB",
    date: "2026-01-25",
    category: "math",
  },
];
